--liquibase formatted sql

--changeset konstantin_mosounov:1 context:local
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('Assignments','$6$rounds=5000$M8lSEVz2poLKbz.J$o3x6JbkYbiFABggBFL2XICN1wPu.3jqbOx9pMqzAmDX1UVF8exPUowECRuBYii4s/os3JqvK/jjuQ4AIjUYab1',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth,impersonate',1800);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('MHEAdminTools','$6$rounds=5000$Z9ETK5vi2JZwF5J0$AMNgix8QTqsBJPwUaX56btHFaBGaPqUhKHGEkxJOvjiaEGA7H0oaceafpnUaTsMCfpSUXHej3gw/RdNq1rVJV/',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth,impersonate',1800);
INSERT INTO account (user_name, password, active) SELECT client_id, client_secret, 1 FROM oauth_client_details WHERE client_id IN ('Assignments','MHEAdminTools');

--changeset konstantin_mosounov:1 context:dev
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('Assignments','$6$rounds=5000$M8lSEVz2poLKbz.J$o3x6JbkYbiFABggBFL2XICN1wPu.3jqbOx9pMqzAmDX1UVF8exPUowECRuBYii4s/os3JqvK/jjuQ4AIjUYab1',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth,impersonate',1800);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('MHEAdminTools','$6$rounds=5000$Z9ETK5vi2JZwF5J0$AMNgix8QTqsBJPwUaX56btHFaBGaPqUhKHGEkxJOvjiaEGA7H0oaceafpnUaTsMCfpSUXHej3gw/RdNq1rVJV/',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth,impersonate',1800);
INSERT INTO account (user_name, password, active) SELECT client_id, client_secret, 1 FROM oauth_client_details WHERE client_id IN ('Assignments','MHEAdminTools');

--changeset konstantin_mosounov:2 context:qastg
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('Assignments','$6$rounds=5000$T5NTwE2awIjisMNP$5BakY/AHcHQ6/3usug1DuxcdAjFUZ5Yu9PJN9jZO8C8PfoERWLZgaJWJK6APSSX39zUNA/2My1DSzOLOMeV8G/',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth,impersonate',1800);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('MHEAdminTools','$6$rounds=5000$VyLfdj/e15iOGbfK$UzrKO33fWD/Ae87W/4ZiR2FjoAa64LBYQddB78JTFdodWkjgRzVE2lSBUJEbMJ33JP8b1k5MHscALMsAQzKlh0',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth,impersonate',1800);
INSERT INTO account (user_name, password, active) SELECT client_id, client_secret, 1 FROM oauth_client_details WHERE client_id IN ('Assignments','MHEAdminTools');

--changeset konstantin_mosounov:3 context:qalv
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('UsageReporting','$6$rounds=5000$J0TgIbDAwCpPO3IA$gFr1V2sE2H36rVfb0qoIeujT9LFjJtQGm4s5A73VwbqRf3kZ//rzzyFmtPkNBr8CC9fhqdol8WyeM0HNNQ58/1',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth,impersonate',1800);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('Assignments','$6$rounds=5000$zmlNCl6KutKIEzAc$2cCWpCBqG/V1u44Bze.HxEPOaxBTVv/SI00IuIaCUItXXc.bYWSC9dh4Y2/u.SJedR6XoMO94uezoTrWxIcNB/',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth,impersonate',1800);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('MHEAdminTools','$6$rounds=5000$8Lb7MW7xzW2XWCp2$ZD8A6V.v6k2vGNdxnI92xhO5f1e9B5vYlShM/EHJyM1eYm7wuE/rMmNFnM4wXGUjNZmE380nWnc96/jmeMEAA1',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth,impersonate',1800);
INSERT INTO account (user_name, password, active) SELECT client_id, client_secret, 1 FROM oauth_client_details WHERE client_id IN ('UsageReporting','Assignments','MHEAdminTools');

--changeset konstantin_mosounov:4 context:pqa
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('UsageReporting','$6$rounds=5000$bSVmlykLamjTrYtj$AemNDcJHDhBZLRiGJu9LrAn3UHHWMvNUFea9vEarS1DP1rBh9lU/Y76BbH1urBaurhMNO8nFX5Njg5fQ5ARq5/',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth,impersonate',1800);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('Assignments','$6$rounds=5000$0vrvOyf2uL7XzOvv$6Un/ndmAcVvlJA/cK3EGAKjLk6qFzlclStjUr.z4aixGRNz2pdEboCpT1blfa0MWV/9ooyNge41eZz4XMtk3H0',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth,impersonate',1800);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('MHEAdminTools','$6$rounds=5000$dEeII3ka1QhyQx87$ZWDEiKFEvKFEM1nWx7s15FG6YnYeEMh.NJw/mEiFYK7Mwf09J7Y1zwRqhWVvQbj1Yvx478DtkYoJc2befia.A/',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth,impersonate',1800);
INSERT INTO account (user_name, password, active) SELECT client_id, client_secret, 1 FROM oauth_client_details WHERE client_id IN ('UsageReporting','Assignments','MHEAdminTools');

--changeset konstantin_mosounov:5 context:demo
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('UsageReporting','$6$rounds=5000$mtvEIjkuuZG5MHyd$WgFYZCstgENSnKtIAk5yxB19VqJaMgrx8TDcEy84MbLXvRv1IkOPeWge0E0exNtwP4.ym1lhThh8xUkESHFC01',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth,impersonate',1800);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('Assignments','$6$rounds=5000$2J96MAcNAAvRgeMV$k7JxAz8bslfqhj8ZSEDlKB7XpPbniaYsE8U3eWR/wFsyjxfXPWJ88X7kMPP6M4ifeiRe1YEBOJE7r/lPfWbiw0',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth,impersonate',1800);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('MHEAdminTools','$6$rounds=5000$30Rc7pFGHwFUsvu0$3eCBbznKGQuqnvoABvAeNPdnVlbxSj9hSxQ2W1YIfTchr4AMZ..S7c4U/Ueaxc3I8IlXamCcofDcg4upoPzdD/',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth,impersonate',1800);
INSERT INTO account (user_name, password, active) SELECT client_id, client_secret, 1 FROM oauth_client_details WHERE client_id IN ('UsageReporting','Assignments','MHEAdminTools');
