--liquibase formatted sql

--changeset pawan_pangty:1 context:dev
insert into oauth_client_details(client_id, client_secret, scope, authorized_grant_types, authorities, access_token_validity, refresh_token_validity) values('test', '$6$rounds=5000$o21o548/rTUas0ZR$OFHOZl5XBNjK1Fm0hSDC5Rfmn0.Y7/IIElXlp51y0EU/rEjoJzBzQ17nqe7MGwB1FOjUBWvzIUpO7tXR09MEr1', 'openid,impersonate', 'client_credentials,password,refresh_token', 'admin', 86400, 86400);

--changeset pawan_pangty:2 context:dev
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('EngradeProvisioningClient','$6$rounds=5000$V06GABS5UhtRzG6h$LACsn3imDgscS0buMR7R28Bk3eJvPhqAo8aIjFeQoREUVspHAVrF6GvSSmdGu9AygN5Kj6LQFvn1p9c1.Dpwa.',NULL,'client_credentials','provisioning,fulluser',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('EngradeStageClient','$6$rounds=5000$UL4ogiw7elbphoQv$dA3m4bnxbPkrNg0yTmVuRkz2k9TVmADHhUHDNs0l3EPkdgoD6eA/xpdOffAE7Embz90E.52LNHXT1WVf.SBcw0',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth,impersonate',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('StudywiseAuth','$6$rounds=5000$kqdBUkNUbCMzZOOa$v5D0ov4otHeZ7DA2QbyENS6330wVf7k.EoHiGyhE2VqboWgEhXU1Oei.nad0gwU3dMESLD7ZiopplpXcsOVDJ.',NULL,'password,refresh_token','auth',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('StudywiseProvisioning','$6$rounds=5000$eMH46F986qfKeFxj$QjxpqQwXqivcKdQdXGQ.6UBYODd2K/Gw8GQgaKH8XKUxSaLCeFuSsKtIjf33oGpO9Hev.2NzYTkWWkB3u4fxl0',NULL,'client_credentials','provisioning,fulluser',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('some_client_id','$6$rounds=5000$h4LznVXRyTIXkpcM$srcyMlHXD8WGTmECOTA.BEpTsK6kw5el6F0Tji9GlVKVSVDz8Z0t60ZLU59Q/fHkxVz/QPgBAxT6IhQzcIcHV.',NULL,'password,refresh_token','auth,impersonate',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('sarav_client_id','$6$rounds=5000$f95plr6rQGYqHhm2$/RyetFk2zLM9m.h2ENdoYSL9kIK7/ljWrMInkW6V6Pyjlbz7DPxlUlWsAR5GyxWFgSwSaki6R8GI9B0/C0qW2.',NULL,'password,refresh_token','auth,impersonate',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('test1','$6$rounds=5000$U5oV6Fd.kz2LEQXw$gEwfwk2Tpvi9nWXqvhaOVmILNTJza/3lvy2OZhhG3rYSz5g2K3qdp.OT6lsoSa5vMlFq1Ih16ltkbgPajV3pX0',NULL,'password','provisioning,fulluser',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('testprovisioning','$6$rounds=5000$XOcDiFK6jp8ycQkf$rrpTCNhv.vb4i7d03gHxmxOK2JSRr5M9jTxuJo/tC8noWmY6oXgHc1SCr8TKHJx/RMBAyczsXNTzniyh0uwmM1',NULL,'client_credentials','provisioning,fulluser',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('StudywiseTest','$6$rounds=5000$BqgcHP6d6shg001z$3.FxakthiZ/EZS.oR.FQAm6U3Ee4jhJB/eizvGJqQUXw9k.X/KmIt4WxTah4PaZI2lzth0pS0JZsTOfHljWZV.',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth,impersonate',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('OrgClient','$6$rounds=5000$nBPsgmGFEVDs85UQ$ajzUfsPTiVEugPW9IAc/6jmskI0y3y8CuG7e4kQzAZFauwH7PiK0iJP9oxNTD9idSQr6AXCpIYQ5rjp00eXwv.',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('Decoupler','$6$rounds=5000$mv6KChunzJCMWEOv$8D0I3eofBA5V4ihwcT85SxUQvmPiHosimoFvOi0RDEUfsYuwQD4Q7NAcRLc0VgGrccghsS3EdGWjakyly5x31.',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',86400);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('MHCampus','$6$rounds=5000$Ay8uf8/V96mm23En$jp0sz2LfUEfebfTggCbU10ObtL4cmEuzV0EJ6LXWzjO6qbPq5hMjmabu/kTa5GHGsvvGvDl8McmQQxSoB4g0u0',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('UNITAS','$6$rounds=5000$mq/.Zmvxwp5/RREv$HCzDRXCQ3PvUtEYc9N7TNV75jTn.vlqiFXERAu5Z7Off067rWdDX7cB/M3sUzVnpKZK8OX9Fj6Wc/VJK7PdEv.',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',86400);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('RMSClient','$!ePNRwISv%Lksupcq6IbtCJq$AdkuPMXH8xu2vn',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',86400);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('MHEPolicies','$6$rounds=5000$6qw/tSrOzNrEPs3S$uxI1pBsrp.4e5Id1G1mGDGXeSY5O8rbQx3pChCvBXKRPerMkysIfPABVLKCpxuhd0m8Ov2.2fMTmAYAggHZqt0',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('Courseware','$6$rounds=5000$0N3JPCtoNn93gHb6$oK/lBEkqcEqTXE3cXawWKywhYhZThHqR/pWLXUQWtB6SfJYElNDk5t1ygTGQOiXhPL7RFwkVfvzV/CLRoKELG1',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('Coursemapper','$6$rounds=5000$7NYSWNhU.r9gvU5m$QRrRX2Ah5xscQSHY7d4wN4Tc/1B3EEH5nrWGeCMPacM7TTWvA7LUBWlXDvSJjosFa6H6.BZJwLMOykdtKAiM10',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('MHEReader','$6$rounds=5000$SHyyH3/mOJ9.1P8t$o0XYgbRokK6.gQVVX1//uzykRFJUQS.NTAWdR6vaN81WQa1GfbQM1GgIhhtbQ6tEdVRuV.cURaKAdVhd8rg0U/',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('Authz','$6$rounds=5000$HU6Jle.lgw15LePZ$TpiYJ1nnEJ9bWSs0Wau9BP7RZ8FYo.UIYX6s3Bovx6trtuawhQ0OCapZrzYrIDHHog1ufn7nBYUHx5S99jhXs.',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',7200);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('LURE','$6$rounds=5000$SxzHFki15BXgOzsg$qf47HwiIfDWxN4sK59WA18jAI1JqhNb082qZ14ROzqFFplF5g2AkSI5XlT9yHWvoAd7BcLYpturTF/0AczR5Z.',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('AccessManager','$6$rounds=5000$tenB3sw76zi7cSUB$CtLmccr8P4Dv9zgNoLPE.AK5wdNgZK2tU.xBqtlRd8Ag2fyQeakxyX.znea91tLDi5K5BMVmo9RxCPmFsuUI31',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('Follett','$6$rounds=5000$fWd3.BLAJWdiWdKv$JUZHm9roJrZURhW.nCamIisLu70vKuSLE9rSeAwunvnIwQ5yXOQb96xm1pp24PxErf9t/lIU4LTCVH8e3UI/M/',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('AssessAuth','$6$rounds=5000$9XjQLkB3Hp5PKQhC$UF7GRPWmPuezEBnrhgjaUljOG4v8rox2jMomXvuF5fYJJ1cFbKaL9HeIQUEhxvUg536lsA4fVikHu/bkFLLyx/',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('OpenData','$6$rounds=5000$oW2hu4gMfM4/0D3G$KStNG0y.M8LsGGgconisfJLJwKTCKXQieGGNM2JnhXKiUZWdRJJop0R71peb.45hZa3uVRxpN8aKMjphCou0W1',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('ENTClient','$6$rounds=5000$QUFyKukZBHFXsnsy$Hk6/ZNc9RgZ0C/IujphhsZlLI/MSulSLxV6h5MAGdmT3BWbfnRnqUUn.HmFwsFMDuzG9yFeRPQGtXat14NCKh1',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',86400);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('DealClient','$6$rounds=5000$O24gK3qRYLp0Jjm6$8WoWSFH09MPdgKQ3HLbzyZrvQTCuAocGxM2IbskV16.KwScqgJbBU1MjsdzuC3kgoNa0wyv6z6G2chAWQWKLL/',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',86400);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('RangerClient','$6$rounds=5000$JbuNuvpLsb.UYw.9$gFH9V/LvnQm60NKk.SQHNSLiDC.YVU2CSDuXqHCJPOjA83UbByHnJ0.UmfHY3P1WMizsBVZZ0H6sIv325UEe40',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',14400);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('RedShelf','$6$rounds=5000$24aEAkccLBfQvA21$YwYApnaaGCFHO14o4sK6RPPIF2pwG07ERZY.HOEN/jgTQjcW6hmkNBHsz86Ibg4OVEE8AW6jZlxE6dLU.TG/4.',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',3600);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('dpgloader','$6$rounds=5000$RvnOv/llU0Gax8Zh$wSl8L/ZiJ61EwmMgJGG18EeUQmdW2xdco6bU1bGciGrpsoXObELTBZmL41vQPVSCwKEBSXXslU8k.XsdxknTT/',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',14400);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('grackle','$6$rounds=5000$OxwfA6pNdilw8.A2$k8UgwS3Xa9OYyTLDNfkkIWEJYGmywrhGbVtB8.57v8e5NJC1gJQpoSrW2BcYKP67hbwkoI4Y4HK7LlhEnknGI/',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',3600);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('mhrweb','$6$rounds=5000$/a9IbaluJQC9ZjlC$uoP6chx/h7gAC4/Xz.mTKsQrbQmkgNxrObc8DbYoQ/y7AEGN8oy3TN94PbyGgm5AdDWU9x.hB3tCAWGs/OSEi1',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',86400);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('mercatus','$6$rounds=5000$jCQyYw2MrHO5ybzd$hQTVO1qzU5NuyyDh4NcDzcev9q9//pINCmX.fe.E1U8UqMqCxKlcPFNcra7W8vKOaQ1D.rXrfx8xd.frnHwvw.',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',86400);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('ProductPortal','$6$rounds=5000$gfTE6pEpFXLRrBCa$zxpBmWGzAvrt2bR5u4mVLsEz1Xbgl9qwCHPYIRI.2QjwdCTyry8WZ4CE0Oixp257LFhIp/NZI2M.OcH5RMvg10',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('gradebookapi','$6$rounds=5000$n66OFZlHhP8lNF.4$uvaWIn7sIpMbbMdRJ79TmupcM18nOQcr3jPSCqKM4DwUky3p1E6mdCFJf8mWkgtfhR3q8mWzFXBzxE/3QCCIM/',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',3600);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('vitalsource','$6$rounds=5000$PY6n/7RwMjv747Sd$ymtd8XZux54KzVotkSWRoFH.1sAemrQQHDfdytXIsjfellwg7d5S2/h1YdL23xmCHd/4idaYoMO69ct1qy3pH0',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',300);

--changeset pawan_pangty:3 context:qastg
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('EngradeProvisioningClient','$6$rounds=5000$Rqh.oNGxcghavoP2$b8Vd2AqQ4oyXFGtUbj5DGQ9RA8mIBgHZ.q6dI4pOAreK1ui9D4dzVi0jR2bUSyyKdF.kZbVBtL3iC860uz/wE.','client_credentials','provisioning,fulluser',300);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('EngradeStageClient','$6$rounds=5000$1X9xWxxgC9yq3R5E$DUu8pB/lBL4X9wpTpTtguQ1eTX978vIYrMJz5I2x.a8JDce4wS8R09YnzLrYoTWC6veNvMuLSFq8B7nizsGUr/','client_credentials,password,refresh_token','provisioning,fulluser,auth,impersonate',300);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('sarav_stg_client_id','$6$rounds=5000$6nk71KX2DKkXlCmA$/CbkC3xh1wzOxHHo47qO1KUJs2wxEK2QOPRR7RCzHDk0UL7Lsx0Tymr0rY406UmYPrUX5MJyWG3dc4ap5.Srt/','password,refresh_token','auth,impersonate',300);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('sarav_client_id','$6$rounds=5000$ubA2wBftHxI6z0DS$SKNg2Lrw3XipSlTz5Eh6lbm8YRwxCmXnOU1ADNrvCf2TOUX71fauJ/SM83otEQggWdlGuCIUVTJldsV.pyWbY.','password','auth,impersonate',300);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('testclient','$6$rounds=5000$afHGO07Z3dLJEuOT$rFSyD9FV73n6CrGhA3OSL5SIRsIn5/y80O2PiQMvYlk4wOGTSKfuJx9Do2oNzD6lqo/aq/4AUSQl95eLKDfp71','password','auth,impersonate',300);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('test_anoosh_1','$6$rounds=5000$wdyGcx41ThmA6aH1$Qpj57MYw5fogJ5abI05hwn5EbSmRdkKZkooqSXbuH0rNjBXRLc.fAiSXDrCqiKpdYwrkl.PXoEPnUIpfTmjVH1','password','provisioning,fulluser',300);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('teststg','$6$rounds=5000$w6IERUhcjx85g8qE$l/4l/ro.erD6qMhtG7CeAmzHHrsnlIpXjUK/bt/JYDvOrHHdd4K9VD/E0JJxJX6DOvxM6BFFI7zfgHRIvccRQ.','password','provisioning,fulluser',300);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('testprovisioning','$6$rounds=5000$rXKUJa2AyOsjFMni$Ry.JFEtZlW9Ud4zvJ46YQdZIbb.D8JQJ7nJ1LzCG9Wzy89zh6TZQ.cUVJEyPJZPgMH0fnEcZB5k1UNue8.tR/.','client_credentials','provisioning,fulluser',300);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('z','$6$rounds=5000$7ZyKNSN4RQH3oMNG$/hdHE22ct2QN31Hd5Ie.fkqDy5uwmi5SEZEXg5pFijz4LQcOp2yjrUmr6pKiUo7vd97oI2axmEEKvsWk9cfAh0','password','auth',300);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('testauth','$6$rounds=5000$Pk0XxAcVjHRv.lX/$yRsFmVbMUrwvJutF//WxvqmMIGRRGju1Y9e5L2Z2DLOL3c.PftgHyplD6zW8Q5o6TKVNgLr5jW5nh01h5zWw51','password,refresh_token','auth,impersonate',300);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('qastgtestclient','$6$rounds=5000$7N732JLLkvOCU5EW$dYTogr0ZU1eWQVWDyT5U688Hhp4FYg3HCFy6iAccgPtYtAb0j7mpRLMrD/PYC8ehexz8tteFZG5slaBE09XNv1','client_credentials,password,refresh_token','auth,provisioning,fulluser',300);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('OrgClient','$6$rounds=5000$hC2avELuNBQvuIo.$h8ieL/SNeQvIc6BBrkMu5BiPqO32wdlccj17Trv3VSdL01GNcnp3CFeVWvCtCAy3c9bHOT9XaR0fPa8iGIefT1','client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('Decoupler','$6$rounds=5000$iCp4JQ7LPg1B0QXx$rb1CqbRajUkOoSyBTTU3nTCLSMyZGlheMn17V8hhWE6yjO21raeCJU60ZZD2gG/mteG5Znhom0cjxM2n2G.vK/','client_credentials,password,refresh_token','provisioning,fulluser,auth',86400);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('MHCampus','$6$rounds=5000$XUXW9hLziIxuD1Yt$xPbUg4xqTeQhOZJHdPhReIKJzOUdURu14lDsGcxKs936nII2CCpXhsvufgOAjzHYKls96T8Vg3BO22G.Ji9k4/','client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('UNITAS','$6$rounds=5000$RskdSH03cqrZbQX8$01wPkASPB.vTB5WBLkHVNpXXoiRMRtNZTeB7TncLcrdldPb33nPtJRZ4lEmg/Ps26mrzgucMxjNfuc3RbIigR1','client_credentials,password,refresh_token','provisioning,fulluser,auth',86400);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('RMSClient','$6$rounds=5000$yp50SWelytwIExpM$NJuJzh8RRtUK5XyPGkJmWnnywWCdkPsQFWWcjesl7XQQ5ONSM.xrcf/79Do5zdpBOycVNi.C.9/evjJR30Icm1','client_credentials,password,refresh_token','provisioning,fulluser,auth',86400);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('MHEPolicies','$6$rounds=5000$EhmiYosLh.x0vZIb$om0Zmmm6xCEV6OpfpaZJm50GAS1NBimD7KsqVuNwM1wAKnynldnxV1Lk99aj9vPmHgQyjjTXqG0GBBoqnlM4T1','client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('Courseware','$6$rounds=5000$pLgOxn/ao7gbGjdZ$bQkBKQyuptWMM.cFigzSkeCITqMI6BWeg9gPr8ujKF/XjSm2eQ4pmeiqjgdAYkKPmp1OrD1aYc59BUr90RNsO.','client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('Coursemapper','$6$rounds=5000$fIKfAPwNRFvmMBzt$zjMqzL5XwqtaP0G7URP1zO8QECUgS9FAKFK.klFLKNLOHgGT64hyqELDcOXQmOLn3w8VR5mbNyxjaJO/zNLoH0','client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('MHEReader','$6$rounds=5000$Py.EyfM/EGwlhwpt$V4rWszP0mAUPuPPZSgFrmaRgoSumvXJ2piEUYjky4F/IHBMXqk.ToJoAUu.mIoY6.tQ79Q5ejoASPmKFs742y/','client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('Authz','$6$rounds=5000$LmfLTJbH43961NV7$zzmbNEvkKq5WPS0dqcSu2sgESD83zf5oek8gFhmtpyQ9W71pokLTR7Z7T7e836DpKeG2ekFfsNr2e.lNlnlIO0','client_credentials,password,refresh_token','provisioning,fulluser,auth',7200);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('LURE','$6$rounds=5000$WTQT9swUszz5ies0$BJ4Yf1ZvZMQ278rL5L1q8/GV4b59cgJOK.yqYKENRPCkift/ERAB.ONCQxjfspIKPVma6B8t./a624ftLmqG4/','client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('AccessManager','$6$rounds=5000$4tc6h3ueXhc3Igwf$Xul7pU.abRTYtyloWcqnt6xMVCF9nuXKAND.7EvrXLMfrS3fU3YM8zMl4NislA6q2GyDPfkVpJDdjQ/Q6nvGl/','client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('Follett','$6$rounds=5000$I2JgD/zEzf/.veIK$dqGa94rt1Nb9FJ2FLAXnK9XwkXce80hzdXtZcfV4XOFhiZDGQAQt8lzWxTzTHib2J.KGXnpWJlJaKL8mWq4JT.','client_credentials,password,refresh_token','provisioning,fulluser,auth',7200);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('AssessAuth','$6$rounds=5000$qTg6LOPxbn6k08Mr$ehwv.YWwsoH7yumH9WHplvaledc2uQi89WXsMm6H9l6FaxInwJyVLMLs3EeCegk47zmNe9vf2X9qiJxu8dlz1/','client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('OpenData','$6$rounds=5000$20jeoCbtzc9OrHfG$YV3qbIOLybPy/ZFDpp5pzr/ds0/mBL4Mh/w/vy2K9j3Qv3zxmtCPOY1sVn6YnnfHi6HUe.gD.izfQgg3uQI6E.','client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('ENTClient','$6$rounds=5000$nKoFjFHnlnG0Pkwc$QJuvsKmSJzpF5Wfq.vb48OIteXfJUUAOe4.yQmk5hzL5YI4Gmq4izwOUpMCZpThfl2ntXL4h5dzFRfuTl0Dwu1','client_credentials,password,refresh_token','provisioning,fulluser,auth',86400);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('DealClient','$6$rounds=5000$B1qBQAbP9sKmNXlo$LCVBk03Ph4mMHNs7JZ9zklySbGH5p/CT2scz.zwabMFWJ3slPndz2teFosDGNRzxx8Il.3giBL4AbQtbmhWJa.','client_credentials,password,refresh_token','provisioning,fulluser,auth',86400);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('RangerClient','$6$rounds=5000$9T9lbkacNGmdxspl$YHgy7Od406Gjxmv2gaajeZp/CCw5fquSY9/7pLN8dm/UdxaGpqo2Mesyi8Szx2lSZGjWzrjveqDJMW6gz.Pd..','client_credentials,password,refresh_token','provisioning,fulluser,auth',14400);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('RedShelf','$6$rounds=5000$oSfgDObzmVOQlO66$mL0eYbENdyEnqjXSyOglo8zER0Ua4tUDnlocI0Qcm9C7BzGZvSjqO8JjaM2JUQGQtQXEd62580tii4AytoUnR0','client_credentials,password,refresh_token','provisioning,fulluser,auth',3600);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('dpgloader','$6$rounds=5000$amOIAF./.h2Uab7p$Hx4hUKCphl9aa066tk91uTFTXf/uKcJhKuF0nuzNiaf5VP0/bYhv2iQMI8x5AUYDidtvtXYvpCE/N8kSOmYsi/','client_credentials,password,refresh_token','provisioning,fulluser,auth',14400);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('grackle','$6$rounds=5000$zowszWxndJYEeopl$te5dqTf60I9BTUWW92QBKNtbboyeu6sXZRyvwUY3aD2YK20d2sw0Q4.bh4h5BHD9vmx8qeeIQLXgWMfQRSxDT.','client_credentials,password,refresh_token','provisioning,fulluser,auth',3600);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('mhrweb','$6$rounds=5000$SwW2YlUZ4ryyWkj.$jhK8KV72L2kbvpBEIWobqRdR/T0lAYHWEi0Z3.Spl44KuoEtipQeNM/VD1ZJLXJ8wcUDeBdBg.QC4QixW6SXF1','client_credentials,password,refresh_token','provisioning,fulluser,auth',86400);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('mercatus','$6$rounds=5000$fFoVS9bIjfU6tqTZ$jyvt5jOblYy.X1Xzxobi5taK8D8YbEIydSpBRlXkWLYR54BET4pQgNvzA3dq4fs84Y3zxxgc4cTr6I22nRMqk1','client_credentials,password,refresh_token','provisioning,fulluser,auth',86400);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('ProductPortal','$6$rounds=5000$1LOD07VGMUNcYYVP$tTQgLNVbgm3f3qeFXEIM8z8Wii5Y6f86g101dHOCA836Jpd1LuNYcJOWj1H38LirxNNy8Uf9rwKAChQytj3BJ1','client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('gradebookapi','$6$rounds=5000$eIEnM7n.kkNXPkg4$eTDqfDtQ7Rp6owoulH0/pws4UW/RMhoOFbUtbyfHQNtJUURZSyunbatp/2GoRve7N3d4WNONTWnq/pwnDy0Dr0','client_credentials,password,refresh_token','provisioning,fulluser,auth',3600);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('vitalsource','$6$rounds=5000$bdymCKjMt6OgSDBi$9UnuAHej7jI.1cxoGP4ItJuH/M.iql7fTc0rhVqh/l9T/K3WVNK7ZkesqCc05anTKeDOqX1yAYwbdiGTemSqq0','client_credentials,password,refresh_token','provisioning,fulluser,auth',300);

--changeset pawan_pangty:4 context:pqa
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('EngradeProvisioningClient','$6$rounds=5000$GgOV1ExspHLAfpeU$m98WiBvxUdacSu5DDdDUX3kTnBk9hiJZSMlQwY94sjjYg7e4IpBKsdkzDE0hTLss.dk0wSrwMvWZjVl3ZqFTG1','client_credentials','provisioning fulluser',300);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('EngradeStageClient','$6$rounds=5000$1o5tpKuqZ.ruN6t9$.uQ5tQpvnPad6b3iryKHV/VVWDQXL2BcOwiBFald4CghxLnw.BG5O9DS72Xu6ydgevRyml6b1Rf2mpZ1nUoEZ.','client_credentials,password,refresh_token','provisioning,fulluser,auth,impersonate',300);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('perfclient','$6$rounds=5000$/UhLqIcfBxAW21cy$DJSJfJu06Wjk6LDDkgNM/Zs4ltlZaLTjCbbIUcxjRjISocNJNChubOei8Tn6w.jzV8KDXNwfayMihMd0eDfjn1','client_credentials,password,refresh_token','auth,impersonate,provisioning,fulluser',300);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('RMSClient','$6$rounds=5000$hjOywterRGpJML4m$/Tt89tTk/pi0S96MtVgblYFZ89D7gKtII3.dPnfj1Q/HjqKEhB5e/jrnkUgKjay0Fip7HpsU8sn5Pupz.FzFL/','client_credentials,password,refresh_token','auth,provisioning,fulluser,impersonate',86400);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('OrgClient','$6$rounds=5000$uwP42dTe59GQbpvw$55TSOr6SB52qXAtYFixYtULvsWMQ8ceefJ8JrTsuVHBZngIf2Iu5iSJvpFCH2u0CsPvJr2DBJeN0RrBq4ybgW0','client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('Decoupler','$6$rounds=5000$T.AQgmDDgOhmEcU9$jKBi5x9SwnSnv4KpRncnpC2f/E.pzket5pwMJoxavcb0DY2Cy8sidWMREBNfUzm25TDxI7kn38WpfhZRECl4T.','client_credentials,password,refresh_token','provisioning,fulluser,auth',86400);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('MHCampus','$6$rounds=5000$KLW3lvnANpxzDiif$qF/JLaHPPPWzeiIuOzPlrr5La4tMvvFhUNLFEmBDMAkXkXwrUXryTM6KXKHcC9jDQlLUftnmspZXCk1mGWNve0','client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('UNITAS','$6$rounds=5000$X2ZI6Z9D9KidjFSw$q6o1oinCnE26Bn7.YbbUpNhreqciV5RcDErR0GIq2iHV2AhvIHIeO0kgnPY0gtTHHf3DYB7115ezW3Kt45CvC1','client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('MHEPolicies','$6$rounds=5000$FkJs7wxwsJeItfY2$4aKUuUjE1G9wCnasPXxsNt4z6WDSofE/WEIIB2waQY.xpSDK6aE8G2Ps0EMKW.ogWISHQQ836B1n1RiwkWKoD1','client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('LURE','$6$rounds=5000$PbEWhxhCiGR.LTvu$zaLdeubzvwOj1pNGCW7jGtJAqjNpQkxXTJRE9vEO0NBg667uua2DNzggOb1Tyn2wrwGKAkaZqtN/6zWreozNb1','client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('AccessManager','$6$rounds=5000$GruS5Q68rc1JOaSl$YrRQEX9BbZWCNbp5j1CG9kMx2oicbyiOgCLL9jD3nMn0luXXcZhJhWNvOJD3GwZLKNNgAaghDvaCnzUFNAL041','client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('Follett','$6$rounds=5000$.IvvF.G0pin6qhaO$AHzupxHy.d/wsnnPl1yj.ZDdz/dQIdO40yu4yi6F0Ch.ceWtG3qmJX1AA8JPEYDDy2kGqCg.CLJyCaqZnUtd.1','client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('AssessAuth','$6$rounds=5000$JWE5XzTBTb9QnHtr$oX1XbkU822Mju8JelLlNogGa00qqmPToDLgJgs5D4SWBaHi4OfTc.XVZ9n8.XP0XqqzFlN8e15bBEUvCsos.q0','client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('OpenData','$6$rounds=5000$hSe2ssNYr4UoDo6R$2TVVIR2j5jh1PNw1xhtyApqc/9j0cT3805pDyDI.7aq/VEPptPTGvpkU4q/zMGeT92tjb26TAdEcHfTztADQZ/','client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('ENTClient','$6$rounds=5000$rIBlCQsdF2LtYYo6$H1AapzCGP.Iel.ME0WRYN6luDp1/CJYSqHIJO8NpDO5RPJGFLmHBATcXjvoqXJY6V/al/4YRpin3nfnDrgf.h.','client_credentials,password,refresh_token','provisioning,fulluser,auth',86400);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('DealClient','$6$rounds=5000$SdWgKKnOnoFU5X8N$dShsjx8kwxhBtvCMbS.Hi.lYFX7PxOfGrMtpi2eGoa2Avk7QzznjBtcFoiLHinSNwfh74YMpPZPIgP7mjOhDU.','client_credentials,password,refresh_token','provisioning,fulluser,auth',86400);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('MHEReader','$6$rounds=5000$cGorEXO57nbPpbUg$kpjfFE3Dev9S5pIaOrjcgwcnDNSON2PADzxpMEwHRODKpEgDkykgHzkiwFrCVziNrVeXCiS7PrcyZhdc1egSg/','client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('dpgloader','$6$rounds=5000$Ddsul4UFKXXF8v48$ySZgwvD.sDb79Ln4C0fqQrMHtHtW1JNEPHqKDvG0gsJR284ZxqL4sZJFmSbqgejdoo1rocoAx7YWFGa/OBJdb/','client_credentials,password,refresh_token','provisioning,fulluser,auth',14400);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('grackle','$6$rounds=5000$NgHnz6EIrmo/2f6d$TYY0lz9PoH3p1Q7DktuYxJibY1fZMENpnEYoZoBrrqDy5VAu1wGappoTahVUgaf7whoi36oqUh8wt.rotTkdf.','client_credentials,password,refresh_token','provisioning,fulluser,auth',86400);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('cuckoo','$6$rounds=5000$QY.Gpce3.GkE8JW5$KoSzcHGt8AG2JCf1d5d1VvrbdEjp1OFvjUyJsb4ePxwG0ftPyXA8oQwCSvRBJ1D2htlcqPBSmXHgitAi0iWiF/','client_credentials,password,refresh_token','provisioning,fulluser,auth',3600);
INSERT INTO `oauth_client_details` (`client_id`,`client_secret`,`authorized_grant_types`,`scope`,`access_token_validity`) VALUES ('Authz','$6$rounds=5000$XLlbpioQ0PjeQJF5$mvJko4c4Sen54GH9iEjEqmHM12dWtTtsUTFw8YOUBjBCyYZYlwZKbiwsI1Nb/qWg26fUednwFR3YpQA96ZmSa0','client_credentials,password,refresh_token','provisioning,fulluser,auth',7200);

--changeset anand_joshi:1 context:demo
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('EngradeProvisioningClient','$6$rounds=5000$IYGiacJjLad5dha4$tQrZ4CDfkBkpyVkpSjgq.DN7Y4aXxInwFpf.1nTrpM/T9JIXgXkoIpA5AdVoi.T44RY8dilHU0lCnwSbOYoM6.',NULL,'client_credentials','provisioning,fulluser',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('EngradeStageClient','$6$rounds=5000$eEjOqVSVhwoZ3VDV$1y1Nh3LTATFDjZXe8N1mUaA0kmsIvG.j46L2eCVzKJTxbdwMMjwLjywBr60sv4WYCXEDfmgNoZyjzxhY1g9Jg1',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth,impersonate', 300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('OrgClient','$6$rounds=5000$UOkyxAimZ6Vz1BBR$BKbseuF0m5WfmyWrxSD2a09b6rELU6YbVmb5pIm2VrtvrwzZYGaBrAvxH5YjEUUyFHDzqsWCSEGeRGb7hDXul1',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('Decoupler','$6$rounds=5000$JZ5wApWy12gxZ6.I$nGoVTWP6ZXb3ZOLYvU8B/SkfigwvTRixNU.U9cichRkyWDlWqITPrdQWnU2HUEuHF69YJ.DjvWu1WMrpLL5di1',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',86400);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('MHCampus','$6$rounds=5000$.aNjUH/6VGZi.B1B$X4HvzsHKQEBxeM.lzQI0m9vVlYVh4/aN.tH1PClGznI3kqzDBrZeC3q5SHKho1OjK4cYO7pJAjtoXMlIjTNIH/',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('UNITAS','$6$rounds=5000$HyN0jo0XJDrYQKK9$9CQ9I5r0hJIwgupRNmMIc8MCkmbnIcmrJqLmws.O96/0b7JPP34JUGAwk.6GkqvurmXOqu/cRKWeBtFn8X/FJ0',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('RMSClient','$6$rounds=5000$3XtTXwS04TEsXFtu$DuGVPkoWwdxMzDcmsGU1FZ7v64gGpjKujagSaa2gLdJemTprQEZ4.deOI2XIEt0kZpqjjiwelK/6NGJQ8WkZj0',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',86400);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('MHEPolicies','$6$rounds=5000$GY36plWbWWcjw3ct$DGvOy393h6PQpB710/UtjnvmshP9ICkDwxxrg9GIAc80nKzQRJct8S70x5Wocooo3Kefdv8j0wk.FVUeTriCm/',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('LURE','$6$rounds=5000$MeJhlG7QRrAvahqR$gWybW3V8Ynh4xLjtfkp6eAVPdpfib70YRokTfGxBV1Ue7l4f5jMrEUJl16XDbgO1GJj538m0swqg4zbVTQeF/0',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('AccessManager','$6$rounds=5000$WC3WB0c0vlNFlWZ5$8MJD5L/Z4Ohqcx6TQmFZX8trXpISTxmnlzmfMlG50po0wRmPz.g8kJkiszOlSio7OWxjnpZ0BnB/TxJ74CUpI0',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('Follett','$6$rounds=5000$/FRTul0skiDgFIam$iyhR5Hxwb/U9tmHjwZSkatO4.INkIhxr68IynBDLDxyO9g8y69D1VKeAd/Ulu/2qkaP29g.MCLh3zx75KlrRf0',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('AssessAuth','$6$rounds=5000$nry3/FNbkheOZ7zy$NvEbI9GjZMF2tfbmvqB6PMCf5XH.Cckz3JG0xcYXLWpy1T.NbBEBJ2RPKZnkMWhS1Hj8x3o6JPesY0iurJeHv.',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('OpenData','$6$rounds=5000$EFz3aPh6JSPyK226$GzNMJ9Q1CKSVL8SxTUIxecmI/R6G0pkzWS2lU5bl9wAOakOHSnuiRUMXqTu3ADtYKVYYAgjK/UUvS2aWt5LjD.',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('ENTClient','$6$rounds=5000$0h1vWL.L3GabOh8y$rBPX1TR.iG.AIyU2VyxCrIVAru.ErGHTbc8UAtF3hclGOqF0jNXvfgGfF1U96eyzRspxTKAXcxrpw4apqRIoL1',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',86400);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('DealClient','$6$rounds=5000$Qn4gu6wKbBW.9J70$vsYY.XfLNqSWOzGs0HP6MXPFY1JAGwQwOtcIIiXDAfL3onDg3eRizRgNjaW/UqiIdT9Mo.QcKjQQMrww9UacG/',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',86400);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('MHEReader','$6$rounds=5000$9CI0Y3XT7ZyAwiJE$wMmCi6sTTfYGlG05hM/RMZDiD5taE6cmcpYY/rq11Tu93seVW.bp0ILjOYCAnVrd1cb2m1jNMkjss3z2V2coM0',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('dpgloader','$6$rounds=5000$Em1ihvp.WU8Pg4Xg$r.WH3uB55XcQ4axzL9ujpphQiH8k5SPFVfrCCKacVqEIyk0ARXP.98GzhAUC3TJq4uljYwCeZ.qJUvziSYWub0',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',14400);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('grackle','$6$rounds=5000$0waYcZLud1ZxDDta$mcosT5FJUqoeH7gJg6vk/A6bEx9kAA.PHflwv70v87PLkB9KCbLJzlQ.6dCHEECfccctoxqVmXcb4dPZGPQbd0',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',3600);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('cuckoo','$6$rounds=5000$s2rZd7LrliDslaZ8$vAo5b.CTF6Xy.DU3TJboMERmxtQ4QqB2AVKJt5yOd2CHvpvLQoz3PbCxpkc9N5OY9g5uw6i4Y9e8yM6iL0MPf0',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',3600);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('Authz','$6$rounds=5000$E4KnxfEnNDwHkbd0$lw1UBLCjcDVyyaHdY3nj1WOAhE3SJAxHF3jnjHx.ckZlfGu5dPhqXXcDC2oTl86fFYtgidSM3FJz7lk5Quukj1',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',7200);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('mercatus','$6$rounds=5000$VhEmAfEEBDfySoHw$YvHuxWu5fzXsBqvd19f9nevjXyLhDpmlYZEReHKUlvmvJeoQU6j.RI8F2YCyrBLNb5cVOAdrqMk6Tydx1sQXG/',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',86400);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('mhrweb','$6$rounds=5000$cmS4h7Zn6Vsy/5f1$n/HDrtgYLGEE8SCkygK5D60vz.xrWgyvDpOS3BHjxNhK1LUIBBYC8Jphe2SlYXwVWE2gWZ2X57Hd5BairKtx20',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',86400);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('AssessDelivery','$6$rounds=5000$lNBPUXQ2nXoFiL97$SgppxWys/nr1CEZLUoAa9VDCG2KUsHN76B4Jv3XMqNMs3r21TokW9DnamGI.YkRExfZMF0x2tejQmFq/gyQC71',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',1800);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('Bento','$6$rounds=5000$XtF287xLiAZjKjR2$FSFd7p6.SDq2Ycw7H760ozuwIA1zHsRpAKiyplFxvJKHcOpdA.oDkhorhJdeEsfbLQjjSGFvlahvwcZiPu6nB/',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',1800);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('SimplifiedLoginClient','$6$rounds=5000$YBov0n8xszLBJ9MN$GxHXAqQpaK9MAQDp54YzghAdiWTwHdxUAVIM9wKtLSeRJnMvqVwpgPuHYm8Roqcx82BEh0XYbpFBSv22la2em0',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth,impersonate',300);

--changeset anand_joshi:2 context:dev
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('SimplifiedLoginClient','$6$rounds=5000$YBov0n8xszLBJ9MN$GxHXAqQpaK9MAQDp54YzghAdiWTwHdxUAVIM9wKtLSeRJnMvqVwpgPuHYm8Roqcx82BEh0XYbpFBSv22la2em0',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth,impersonate',300);

--changeset anand_joshi:3 context:qastg
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('SimplifiedLoginClient','$6$rounds=5000$YBov0n8xszLBJ9MN$GxHXAqQpaK9MAQDp54YzghAdiWTwHdxUAVIM9wKtLSeRJnMvqVwpgPuHYm8Roqcx82BEh0XYbpFBSv22la2em0',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth,impersonate',300);

--changeset anand_joshi:5 context:pqa
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('SimplifiedLoginClient','$6$rounds=5000$YBov0n8xszLBJ9MN$GxHXAqQpaK9MAQDp54YzghAdiWTwHdxUAVIM9wKtLSeRJnMvqVwpgPuHYm8Roqcx82BEh0XYbpFBSv22la2em0',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth,impersonate',300);

--changeset anand_joshi:6 context:qalv
REPLACE INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('EngradeProvisioningClient', '$6$rounds=5000$9rQ8A5R69MPHkVrM$Yk/PAbR4lLBwB77klmgvmz8UuEXk4gXwyBOPeO4Rnbw2B4mLk4.u3WJiGjn3ldCKpxmCOd5OMhVCRUzmAl3eH/', NULL, 'client_credentials', 'provisioning,fulluser', 300);
REPLACE INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('EngradeStageClient', '$6$rounds=5000$cS1aHnXeCXr/K6wI$QGXfOPDzdSXmGOA0.jxKKGEEELLp/9WbNduOYC2c7ozX0dtlkShd6gy/ACl4IvOdgtcjxOWhPo319YiEaaq7S.', NULL, 'client_credentials,password,refresh_token','provisioning,fulluser,auth,impersonate', 300);
REPLACE INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('OrgClient', '$6$rounds=5000$sRPDUQhy81Xu1yuy$ce78lGUnb51zglHFUJnehzunRazKDASVx0DSuREkdNmlcXGp6e5/zVdo79hs0i4KcT4mT/kpTNuDTl0ylHIN6/', NULL, 'client_credentials,password,refresh_token','provisioning,fulluser,auth', 300);
REPLACE INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('Decoupler', '$6$rounds=5000$byc31eTMlLkl9ut6$AM52R0NBLHaWBmagrhLM71/38SixWcwUbP5NFlY2MbeTLpFs5A.aQg/5LyFoPersrBUyKfjE3t3U3Nq/q/uvA0', NULL, 'client_credentials,password,refresh_token', 'provisioning,fulluser,auth', 86400);
REPLACE INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('MHCampus', '$6$rounds=5000$tggcQv4nUVD2PyHi$2aBlVeIqWbsyElVLKcSWXgg9Pi3blqvZn4GOtlp0JEB7ql5fECmVvnCtdPU532bZCByotdz1AJy/S0MeQV585/', NULL, 'client_credentials,password,refresh_token', 'provisioning,fulluser,auth', 300);
REPLACE INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('UNITAS', '$6$rounds=5000$TIUlPB7SWh150JlH$S3xhn3idYqK/AdvGzgL1aZ8HdCkJrNZ/nE30ieADOFuU9IMzDytIkq7rRKmE4i2K9F54J3KPuirkXczguRd5h0', NULL, 'client_credentials,password,refresh_token', 'provisioning,fulluser,auth', 300);
REPLACE INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('RMSClient', '$6$rounds=5000$EmW/fBNxz3R0eC9S$MmDcP/KT7UZbgvBbXJRLlv4dXW.OyAClfzyBaf4xIXytyEz/vA5BwJNsz1irFf8VInyvkqso9MZrmpYTmgcGr.', NULL, 'client_credentials,password,refresh_token', 'provisioning,fulluser,auth', 86400);
REPLACE INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('MHEPolicies', '$6$rounds=5000$VIZkWIhquRDdMYj9$2zS1pGRe1eh/DnCmXzIkxTuUCIR95eTxR4Uv/wGuWGkgI10sZrhyW/xkn5BXXdRO5ZhUodhIIKFmNh2mM6Mzv1', NULL, 'client_credentials,password,refresh_token', 'provisioning,fulluser,auth', 300);
REPLACE INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('LURE', '$6$rounds=5000$wWX/ou69jYYb9yG5$epO34kd27sUWgVADi4bR/Fi3YfHci8PmWdEtgt1gHvrwVZZP3GoephyOP2u4af0zrsfd08eazKPHOdgTr4Q8R.', NULL, 'client_credentials,password,refresh_token', 'provisioning,fulluser,auth', 300);
REPLACE INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('AccessManager', '$6$rounds=5000$L8Vc7F9WZcpRDvqH$UF0YdKDpfNUGjkDQPQvkyj5hTqaL16t77A.gk1.zvnGAdziCZC4wIhb5EN26GAvUgAVtEyhoNEGaE4TrprqY8/', NULL, 'client_credentials,password,refresh_token', 'provisioning,fulluser,auth', 300);
REPLACE INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('Follett', '$6$rounds=5000$RtZYHyGJSb.d1jaY$rW4PAquNZhDAZnG/3zrzBkbUlFP2qlSt54ERGRiNxK9YgnNjifZUEsVPe221A4hicaKIgtHVd6.4DeogHK.gX.', NULL, 'client_credentials,password,refresh_token', 'provisioning,fulluser,auth', 300);
REPLACE INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('AssessAuth', '$6$rounds=5000$8DNfH2.2FPURXZtR$FfCvKitsk5Jo7J4RhMRDRnB/.JMnn61qrYHTarAAHCOrhibKfHO3p/uKft8012.ktzl1Z6WWY73ihYP1QzuCM.', NULL, 'client_credentials,password,refresh_token', 'provisioning,fulluser,auth', 300);
REPLACE INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('OpenData', '$6$rounds=5000$qw5bh2RwzYV/5QxE$LOqPaJjn/dAZMFKKZkSI8FDw/3sHT1APcrNC8dDWyfcbT09NMB9/lC4RScWm.h/2FmRmW7hSewmb9xGmGhwWk/', NULL, 'client_credentials,password,refresh_token', 'provisioning,fulluser,auth', 300);
REPLACE INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('ENTClient', '$6$rounds=5000$N8kfQAutCSDJI1o7$hs2VWsDZ1DjIBhqPGPKj6XKa.z73r.J5uVvuwcuizz57MI4mfo4ROxxahEHQDoU7.lANPonIqDD/d73WWb9iS/', NULL, 'client_credentials,password,refresh_token', 'provisioning,fulluser,auth', 86400);
REPLACE INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('DealClient', '$6$rounds=5000$XyIJOJrV.evXCTxO$2EIkZKKb3AG1wXvU7ohLX8CqWZCkq.KfnO0JBEacCuKOGdlcQZbsmqqNj6MJGOjYAIn2P.UCw2wWWKZJoUtf51', NULL, 'client_credentials,password,refresh_token', 'provisioning,fulluser,auth', 86400);
REPLACE INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('MHEReader', '$6$rounds=5000$jCp0jvGeqQ1xNqTR$Wr1167kiTY5IOE541uslOmEdcMnsq8oB/aOUIvAPRJD6ESU6/HXcbfwhmHZcgIwlm9ebaEab9VyleT3z5L.A81', NULL, 'client_credentials,password,refresh_token', 'provisioning,fulluser,auth', 300);
REPLACE INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('dpgloader', '$6$rounds=5000$VpZoUB8winNrckbk$gDNXmxuHIDr3X6HcYvJ3GNEedWm3z5N0KeMtVvrs/xEQntzsf4jklaR0blIUsuthfiPaVzEbKKuZfGaSumw6G0', NULL, 'client_credentials,password,refresh_token', 'provisioning,fulluser,auth', 14400);
REPLACE INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('grackle', '$6$rounds=5000$ARXvM.B6GJXVJ5YN$6O2IUAnEfwaC5MwACioRMu0e53JmI.Tq7T3F3N//5FEaiiZd.BYKc/BDpx.TpgdWapugsEPc5F3pIO8joZBHj.', NULL, 'client_credentials,password,refresh_token', 'provisioning,fulluser,auth', 3600);
REPLACE INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('cuckoo', '$6$rounds=5000$z3Ajif7zmQ7bF/ly$t.Pb6sNyNPOWYY1VQtzWqf40PeLi/H3UXsSt5q53DbH0bZkS6lehiVYSArxHkyNig9VbNGYjTxLt8zF2uZenv0', NULL, 'client_credentials,password,refresh_token', 'provisioning,fulluser,auth', 3600);
REPLACE INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('Authz', '$6$rounds=5000$rxFn4BQtj.lC8YmB$Fp.cJ5AboZ4uZMxMFOtiAYE2AKr3MCLlDAuESwJullcNctrP8cK6kUJS2se.zFK63em3/OIZ2OzqVAPtaqhGJ.', NULL, 'client_credentials,password,refresh_token', 'provisioning,fulluser,auth', 7200);
REPLACE INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('mercatus', '$6$rounds=5000$nNjVf3SvCisbiZ16$R069npTgVCKIERVWbIUiD/IzOL/rhMYrLady0dBTCdRHC6fkpRHiwcq1OJAwqqk.xgVKe4h5JJ/HhZfqH/But1', NULL, 'client_credentials,password,refresh_token', 'provisioning,fulluser,auth', 86400);
REPLACE INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('mhrweb', '$6$rounds=5000$E./azOdfJ596.hoL$2/2PXmcSeiOPIKwyEnFhtM2zBr2c81NxNir38OviCMSO7Is9TYaLVuOFd6JJ.pMx0XQ9gTvHuZePY9d/pQrCB1', NULL, 'client_credentials,password,refresh_token', 'provisioning,fulluser,auth', 86400);
REPLACE INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('AssessDelivery', '$6$rounds=5000$kuJmMu3NbryGxIZm$RFaNbzooNqibCDMEOYHEd1dltwa9BdQRwGMAJv7ZPdPzCv6zfMsBUP/X.5jGBXN/baXlQDeLsUO5T9v8Q.dHn/', NULL, 'client_credentials,password,refresh_token', 'provisioning,fulluser,auth', 1800);
REPLACE INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('Bento', '$6$rounds=5000$Ed2KsaQh24UACQmp$PNlO0xCb4kSG1BFnF56Wp9xwx21QykUu0utngnfaKAdgMaTZy4T8Wkc0y3tsE6c18NI/pNKdqUKGW/8UZV2e//', NULL, 'client_credentials,password,refresh_token', 'provisioning,fulluser,auth', 1800);

--changeset anand_joshi:7 context:prod
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('openLearning','$6$rounds=5000$8Pxd/UnNdaPZnkCI$rN4qmtCXxGU5UBiufOyeVh.E9wLg5OP.Tynbr8/biGG78f6xNNCwVF3s/78n0O0DEm9bBQrJDoNGr8fJl1OKu1',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth,impersonate',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('qualityAssurance','$6$rounds=5000$YVJXTVKxK8U9HDKN$Go0t3XLo/9poE3rvBZ/RIrcAXH./eOLQ2cR6GJj9.Kso27IS77NzRPyYrF5lAEIm7sDArd.yxRGr9EIbBbbbX0',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth,impersonate',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('Studywise','$6$rounds=5000$urHOS2GJiTBHwwQx$TGN.66CQFiDYRKrSI5hpk3aUPhhgEV15.PPMtj6GjRbu.EFKrYSKq3av721eQn5FVWMIOgHYCI7GKG9RJJ5W7/',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth,impersonate',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('OrgClient','$6$rounds=5000$AtPSmY7epY5hhOox$xg91PD7yeHXhke2i4IJW6MgMmnVJEMjK4.zHt8kf16RmORLn0ATmYC2lwNfV4cLEW3FOsVvANFWiiTXgHY8Ih/',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('Decoupler','$6$rounds=5000$RQE27E6awI/cJFqK$M7zq3OFxk.o8MfRyO.U5gjZ7F7rRIGps03P4DLzLIsgukJ0gfK7DDGzfJRO/pwp9oO4K.3/MXNLNocjbfrnum/',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',86400);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('MHCampus','$6$rounds=5000$6ydU0jBJ4VLSxAOb$N2VAwLhm6cb6ym1H/zuEU/Y8djBNlUsTdjPMlz/UZCweTp7IQcScUKc7qQqFafXTpVu7D/8m812b2L7jbRfi10',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('UNITAS','$6$rounds=5000$mopcZt/9y3sA7QP7$E90gilg9p/o0lOSsjHevt39Nl3/GDaxMAa24mVq2GZaOQD7ZbLFq9ayljTGV5q.j6I2OF/4BcM.FbLGifPQFn.',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('RMSClient','$6$rounds=5000$PBdK5IUHd48WQU2T$q6pvkatO3gs2u7QQ90R/er0WcrWzyne7wsuQWDdsSduhw3kLl7.NlOXtf2VO/Ft9FYZK2TTnOzCiWr4hguhz5/',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',86400);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('MHEPolicies','$6$rounds=5000$660UIEcsfTnm2gwm$o0byXDMjQ7FOSwAReRweA8BgWjbkoRcedTty1LcxA5K0ZkGJ8ZkBh3T9prhYQxmp.0hy.Hbl/AU4vlt75G1k00',NULL,'client_credentials, password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('EngradeStageClient','$6$rounds=5000$7SS.fnpXXFnhcRg9$ANSQm9OpdmZ/efwWtA5C1lqvpLHiJCKY7PIqxKs/IAXlHmeS5YcpUbEbfFDSmyOaO19p7AXcpTQy9Hv.ltfEe1',NULL,'client_credentials,password,refresh_token','auth,provisioning,fulluser,impersonate',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('LURE','$6$rounds=5000$pFvVakoSdRJKafpi$L5rL4.Dz4rRx0asBzxLkYpGgfEMDr00yB6YrNx9SK2zSNW7r.yeE.KjKudOCwR2Zhji9uS99Yg7BrXKMmo9nO1',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('AccessManager','$6$rounds=5000$j52O5sr7i2uTsntC$CkCAuceInuDUA5fxtcNm09m3eduCqRo2jlX4FLMIOQLbnm23RijVoU3.dB6nJHZbElXmdtu8L6dIbpHAO.wXL0',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('Follett','$6$rounds=5000$OM9DGhFslRbLUe/8$S79lbPdzyDzKCYxbFz9vnl110zHQQI6tUmZDnxAsNJwm9zp.e.m4sUGFd.aqCoCvgNFlnn7ZctR5Zd6ZibT6r0',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('AssessAuth','$6$rounds=5000$sg3bPeZ/aac6IO/0$r8dX6LTSYjw7qyA0yMnDATGBPNDa3QUQKFSLyQ/H4jXAlwcfe5RxuUEXCKz6xPJJsTRcIMlZJB40iebGSuUSY/',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('OpenData','$6$rounds=5000$83IJcciLthf2kMKS$Y8C0PEbCsZbIjFcTOEnqmJ.8r8kOwwGtHA2CtRbEmbKJeaeD4pog4e6eIxvWMt0KO5FZjdHNNwHMSiN/hVNi00',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('ENTClient','$6$rounds=5000$HfvB4ws4rsN8JJl.$toWFvgIWkzfUip5MX.NsA4jM5FHUON7ecIk5JdXMt14EgKqdPi.BE0eI2bSEGs3mz/Rjl5udGEefkjOOCtQ0B0',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',86400);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('DealClient','$6$rounds=5000$U6ASql/3CZA1jDRK$Si7SMcpE0X0tT0Om6I0gxAzpaVyxWekTCfj06Wek2uWUILb83tfS1NkXjuu4D/uHShG.ikL1qNHTTFBIqoU8H0',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',86400);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('MHEReader','$6$rounds=5000$wAwYdU3fATl1g176$7fGr/15fgyO3igUDP62ZwXAgj0TIFUlBc9WdmLNrjhK1B50AtlS87eM8r8S0s7e54tQJkjcS1s8rlnvyWjxUE0',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',300);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('dpgloader','$6$rounds=5000$aa0dwD7dgj8ZUWQ4$w/oHsbvrqu.TJsTrj8M6R.3KZzMZkM8BjLtHgILajbJMAeutDE.xTJa9VnNFr1Vr9mNhWzqXtrxLHlQG37c7B/',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',14400);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('grackle','$6$rounds=5000$VV5NMybyBxnrhd9f$Y28PYi/Mou2O4t8gQQVgu.XIQcWaAn5xpDMiwoOqf7lrz1tbcz2S7MmWCKMLGja10Pe65ysutYmbAaKobb2Cj1',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',3600);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('cuckoo','$6$rounds=5000$ziMWbTvwSWDFvpr8$Xs06bGX90MjEUuxBQciBBrXFi6pLl/7pyxqI4N8xE5sx4oD9zllhqOQl90eoK0CvXZ1f4ff6BLpZez2ov19Nh.',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',3600);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('Authz','$6$rounds=5000$dpyHJ3LC5fGnq0DC$fLyVpsBzO0tUoWcdAbFHXzl/mXZsS5koK3M0ncj1MhnGIuhV47ULVHqAuRa/I36um/3/JE.bfrjtgMmLD26CZ.',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',7200);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('mercatus','$6$rounds=5000$zQW.loZaSxKrk7ZP$492Vhlk8Brg8EZqT6I9s/ttdS4jjIbjs8SPMs57fauXZzOrEJbKbTLqjNdMTKV5E2nH4fdKmub2oukcvF8z6//',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',86400);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('mhrweb','$6$rounds=5000$H/0KWOjq67WuXjxK$XOPKp98hXw1fn/IAkEObtfANS/KZnZl7hEF.UKK6CTC.OW8cPWgUa1z71SpqNxq2FYu6YI.z890HcnwIdVcmM0',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',86400);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('AssessDelivery','$6$rounds=5000$m9hF8tq2uOfv6T25$D7LjX4or1C.IDpz5UdKnegt1SEBd6i6pxu1p2lMHVulUF9jpLiHw7WnoRqZphRaBJhBUPzNE/XYHVwsVU8h5v/',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',1800);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('Bento','$6$rounds=5000$e5W7eFgWnHv0xcGz$Om1c9eicJknu0opdbTgWjlB5HljwY8WKon713BfmzmumHXfWy/Oqgio0J5Dm8dVClylVJNHzYaUar/OuyMjmb/',NULL,'client_credentials,password,refresh_token','provisioning,fulluser,auth',1800);
INSERT INTO oauth_client_details (client_id,client_secret,web_server_redirect_uri,authorized_grant_types,scope,access_token_validity) VALUES ('SimplifiedLoginClient','$6$rounds=5000$glNcfsUEqsQAys7U$WoVIVgeO7Sk7chhy5nOfHeC5zHnFkdaIosgiEKvrjJmVuSbnEYZJAiI2mLeqETsCO7fhEzok7aBAZuLKesgiZ1',NULL,'client_credentials,password,refresh_token','auth,provisioning,fulluser,impersonate',300);

